<?php

/**
 * Plugin Name: Woocommerce PDF Invoices Tax Based Rendering
 * Description: Changes the title (based on order tax) of PDF Invoices generated by the WooCommerce PDF Invoices & Packing Slips plugin . 
 * Version: 1.0.0
 * Author: MySite Digital
 * Author URI: https://mysite.digital
 * Requires at least: 4.5
 */


namespace MySiteDigital\WooCommerce\PDFInvoices;


if ( ! defined( 'ABSPATH' ) ) {

    exit; // Exit if accessed directly.

}


final class TaxBasedRendering {
    
    /**
     * ThemeSwitchaToolbar Constructor.
     */
    public function __construct()
    {
        add_filter( 'wpo_wcpdf_invoice_title', [ $this, 'invoice_title' ] , 999, 10 );
    }

    public function invoice_title( $title, $invoice ) {
        
	    if($invoice->order && $invoice->order->get_total_tax() > 0){
		    return 'tax invoice';
	    }
	    return $title;
    }
}


new TaxBasedRendering();
